kind: pipeline
name: jkd7

steps:
- name: test
  image: maven:3.5.0-jdk7
  commands:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - mvn test -B
------
kind: pipeline
name: jdk8

steps:
- name: test
  image: maven:3.5.0-jdk8
  commands:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - mvn test -B
