kind: pipeline
name: jdk7

steps:
- name: test
  image: maven:3.5.0-jdk-7
  commands:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - mvn test -B
------
kind: pipeline
name: jdk8

steps:
- name: test
  image: maven:3.5.0-jdk-8
  commands:
  - mvn -B verify
